### ISSUE TITLE
Error received when using this module

### ISSUE THREAD

**Issue by jasonburrows** [tiangolo/ngx-http-client#1] opened 2017-12-13 23:49 UTC
Using Angular 4.4.6, cli 1.4.9.

After replacing Angular's HttpClientModule with this one I get the following error during startup:

> ERROR in /Users/user/Development/project/node_modules/ngx-http-client/src/client.ts (386,13): Argument of type '{ fromObject: { [param: string]: string | string[]; }; encoder: WebHttpUrlEncodingCodec; }' is not assignable to parameter of type '{ fromString?: string; encoder?: HttpParameterCodec; }'.
>   Object literal may only specify known properties, and 'fromObject' does not exist in type '{ fromString?: string; encoder?: HttpParameterCodec; }'.

**Comment by tiangolo** [comment] 2017-12-14 07:29
Hmm, I see. 

Could you please try using it with a new project from scratch using the same version? That will help us define if the problem comes from another package, the environment, etc.

And also, could you try using it with a new project from scratch using the latest versions (Angular 5.x, CLI 1.6.x)? That will help us find out if the problem is due to the Angular / CLI versions.

**Comment by tiangolo** [comment] 2020-04-12 09:52
I imagine that you solved your problem, so I'm gonna close this project now.

Otherwise, please check the note: https://github.com/tiangolo/ngx-http-client#notice

**Closed as completed by tiangolo** 2020-04-12 09:52 UTC
